dist: xenial

language: go
go:
  - 1.11
env:
  global:
    - PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$TRAVIS_BUILD_DIR/.config
    - GO111MODULE=on  

matrix:
before_install:
  # Install liboqs
  - sh ./.travis/install_liboqs.sh &>/dev/null  
  include:
    # Ubuntu Linux 16.04 gcc5.4
    - os: linux
      compiler: gcc
      env: 
        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib 
      before_install:
        - export CXX="g++-5" CC="gcc-5"
        - sudo apt-get install autoconf automake

    # Apple OSX LLVM version 10.0.0 (clang-1000.11.45.5)
    - os: osx
      osx_image: xcode10.1
      compiler: clang
      before_install:
        - rm -rf /usr/local/include/c++
        - brew update
        - brew install gcc6

    # OSX gcc6
    - os: osx
      osx_image: xcode10.1
      compiler: gcc
      before_install:
        - rm -rf /usr/local/include/c++
        - brew update
        - brew install gcc6
        - export CXX="g++-6" CC="gcc-6"
        - sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-10.1"

notifications:
  email: false
  
script:
  # Run the examples
  - go run liboqs-go/examples/kem.go 
  - go run liboqs-go/examples/sig.go 
  
  # Run the unit tests
  - go test -v liboqs-go/oqstests/*
